export let data = [
  {
    page_styles: {
      typography: [
        {
            name:"heading1",
          style_type: 'Heading 1',
          font: 'Oswaldo',
          size: 90,
          weight: 300,
          style: 'italic',
          color: 'black',
          example_text: 'Heading example Font',
        },
        {
            name:"heading2",
          style_type: 'Heading 2',
          font: 'Lato',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Heading example Font',
        },
        {
            name:"heading3",
          style_type: 'Heading 3',
          font: 'Roboto',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Heading example Font',
        },
        {
            name:"heading4",
          style_type: 'Heading 4',
          font: 'Oswaldo',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Heading example Font',
        },
        {
            name:"heading5",
          style_type: 'Heading 5',
          font: 'Moon Dance',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Heading example Font',
        },
        {
            name:"heading6",
          style_type: 'Heading 6',
          font: 'Oswaldo',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Heading example Font',
        },

        // pragraphs
        {
            name:"p1",
          style_type: 'Pragraphy 1',
          font: 'Oswaldo',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Pragraph example Font',
        },
        {
            name:"p2",
          style_type: 'Pragraphy 2',
          font: 'Oswaldo',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Heading example Font',
        },
        {
            name:"p3",
          style_type: 'Pragraphy 3',
          font: 'Oswaldo',
          size: 90,
          weight: 'bold',
          style: 'normal',
          color: 'black',
          example_text: 'Heading example Font',
        },
      ],
      background_color: '',
    },
    id: 1,
    name: 'Home',
    hide: false,
    page_url: 'home',
    home_page: true,
    base_url: 'https://ciaone-1.editorx.io/mysite/',
    settings: [
      'Settings',
      'SEO Basics',
      'Social Share',
      'Rename',
      'Dublicate',
      'Edit Page',
      'Hide',
      'Delete',
    ],
    page_settings: {
      page_info: {
        page_name: 'Homepage',
      },

      permissions: {
        type: 'everyone',
        password: '',
        members_type: 'all_members',
        selected_members: [
          'cigognini.matteo@gmail.com',
          'andre.scaglia@hotmail.it',
        ],
      },
      seo_basics: {
        page_title: 'string',
        meta_description: 'string',
        url: '',
      },
      social_share: {
        og_title: 'Home',
        og_description: 'string',
        url: 'home',
      },
      advanced_seo: {
        robots_meta_tags: [
          { type: 'noindex', value: true },
          { type: 'nofollow', value: false },
          { type: 'nosnippet', value: false },
          { type: 'norarchive', value: false },
          { type: 'noimageindex', value: false },
          { type: 'max-image-preview', value: true },
        ],
        additional_tags: [
          { type: 'url', value: 'https://www.mywebsite.com' },
          { type: 'og:site_name', value: 'mywebsite' },
          { type: 'og:type', value: 'website' },
          { type: 'og:url', value: 'https://www.mywebsite.com' },
        ],
      },
    },
  },
  {
    id: 15,
    name: 'Page 2',
    hide: true,
    page_url: 'page2',
    home_page: false,
    page_styles: {
        typography: [
          {
              name:"heading1",
            style_type: 'Heading 1',
            font: 'Oswaldo',
            size: 90,
            weight: 300,
            style: 'italic',
            color: 'black',
            example_text: 'Heading example Font',
          },
          {
              name:"heading2",
            style_type: 'Heading 2',
            font: 'Lato',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Heading example Font',
          },
          {
              name:"heading3",
            style_type: 'Heading 3',
            font: 'Roboto',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Heading example Font',
          },
          {
              name:"heading4",
            style_type: 'Heading 4',
            font: 'Oswaldo',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Heading example Font',
          },
          {
              name:"heading5",
            style_type: 'Heading 5',
            font: 'Moon Dance',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Heading example Font',
          },
          {
              name:"heading6",
            style_type: 'Heading 6',
            font: 'Oswaldo',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Heading example Font',
          },
  
          // pragraphs
          {
              name:"p1",
            style_type: 'Pragraphy 1',
            font: 'Oswaldo',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Pragraph example Font',
          },
          {
              name:"p2",
            style_type: 'Pragraphy 2',
            font: 'Oswaldo',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Heading example Font',
          },
          {
              name:"p3",
            style_type: 'Pragraphy 3',
            font: 'Oswaldo',
            size: 90,
            weight: 'bold',
            style: 'normal',
            color: 'black',
            example_text: 'Heading example Font',
          },
        ],
        background_color: '',
      },
    base_url: 'https://ciaone-1.editorx.io/mysite/',
    settings: [
      'Settings',
      'SEO Basics',
      'Social Share',
      'Rename',
      'Dublicate',
      'Edit Page',
      'Hide',
      'Delete',
    ],
    page_settings: {
      page_info: {
        page_name: 'Page 2',
      },

      permissions: {
        type: 'everyone',
        password: '',
        members_type: 'all_members',
        selected_members: [
          'cigognini.matteo@gmail.com',
          'andre.scaglia@hotmail.it',
        ],
      },
      seo_basics: {
        page_title: 'string',
        meta_description: 'string',
        url: 'page2',
      },
      social_share: {
        og_title: 'Page 2',
        og_description: 'string',
        url: 'page2',
      },
      advanced_seo: {
        robots_meta_tags: [
          { type: 'noindex', value: false },
          { type: 'nofollow', value: true },
          { type: 'nosnippet', value: true },
          { type: 'norarchive', value: true },
          { type: 'noimageindex', value: true },
          { type: 'max-image-preview', value: false },
        ],
        additional_tags: [
          { type: 'url', value: 'https://www.mywebsite.com' },
          { type: 'og:site_name', value: 'mywebsite' },
          { type: 'og:type', value: 'website' },
          { type: 'og:url', value: 'https://www.mywebsite.com' },
        ],
      },
    },
  },
];
